- hosts: web
  become: yes
  become_method: sudo
  tasks:
    - name: install packages            # скачиваем пакеты на сервера группы web
      apt: name={{item}} state=present
      with_items:
            - python-dev  
            - vim
    - name: Starting OpenSSH Server    # перезапускаем ssh
      service: name=ssh state=restarted

- hosts: web
  tasks:
      - name: get url     # ищем слово Hello на нашем сайте
        get_url:
            url: http://{{ansible_host}}:3000
            dest: /tmp/index.html
      - name: read html
        shell: cat /tmp/index.html
        register: html_contents
      - name: check_html
        when: html_contents.stdout.find('Hello') != -1
        debug: msg="Success!"
